"package: browserslist-config-anolilab":
  - changed-files:
      - any-glob-to-any-file: "packages/browserslist-config-anolilab/**/*"
"package: commitlint-config":
  - changed-files:
      - any-glob-to-any-file: "packages/commitlint-config/**/*"
"package: eslint-config":
  - changed-files:
      - any-glob-to-any-file: "packages/eslint-config/**/*"
"package: lint-staged-config":
  - changed-files:
      - any-glob-to-any-file: "packages/lint-staged-config/**/*"
"package: prettier-config":
  - changed-files:
      - any-glob-to-any-file: "packages/prettier-config/**/*"
"package: stylelint-config":
  - changed-files:
      - any-glob-to-any-file: "packages/stylelint-config/**/*"
"package: textlint-config":
  - changed-files:
      - any-glob-to-any-file: "packages/textlint-config/**/*"
"documentation":
  - changed-files:
      - any-glob-to-any-file: "docs/**/*"
